### ISSUE TITLE
Can't add .icloud.com server

### ISSUE THREAD

**Issue by dstorozhuk** [David-Development/Task-Sync#11]
What is the correct settings for icloud account?

**Comment by David-Development** [comment]
Do you use Thunderbird for you calender? I think it should be the same link. I'm not using apples services so I don't know which link it has to be exactly. But the link must point directly to the list of ical files. I think it should be possible to access the list of ical files from you browser as well.

Here are some tutorials how to get the url for icloud. 
https://p[xx]-caldav.icloud.com:443/[uniqueid]/calendars/[name] 

(German)
http://finallysolved.wordpress.com/2012/04/30/so-bekommt-man-den-icloud-kalendar-in-thunderbird-lightning-unter-windows-integriert/

**Comment by dstorozhuk** [comment]
I found the way to get icloud calendars urls but i see the app is very baggy. 

After I added new task and press "sync", the new task is disappeared from android and appears on my mac. 

When I trying to add new reminder on  mac, it appears only on mac, not on android device.
