### ISSUE TITLE
Sorting of Tasks

### ISSUE THREAD

**Issue by tlaerm** [David-Development/Task-Sync#13]
Hi David, 

I would like the next (by closest date) to be displayed first. Somehow it ist displayed last (even invisible at the bottom of the list). Sync is with Owncloud 5.

Anything I am doing wrong?

**Comment by David-Development** [comment]
I think you should enable "Order by Start Date". Then your ToDo's will be sorted like the following:

e.g:
08.12.2013 Test1
08.11.2013 Test2
08.10.2013 Test3

The newest items will be listed at the top of the list (even if they're in the future). Or what sorting do you expect exactly?
