### ISSUE TITLE
Does Task Sync work with Baikal

### ISSUE THREAD

**Issue by pascal06** [David-Development/Task-Sync#15]
Hello,
I installed Task Sync and JB Workaround on a Samsung GT-S7710 Android 4.1.2.
I've got a Baikal server that work perfect with a bunch of app on my phone and on my PC.
But it doesn't work with Task Sync, it "failed to authenticate", whereas a free task app (https://play.google.com/store/apps/details?id=org.dmfs.tasks) works perfectly with Baikal
Can you help me ? Thanks in advance.

**Comment by David-Development** [comment]
Sorry for the late reply. I'm going to check this in two weeks (Sorry I'm really busy atm).
Probably you can offer me a test account? This would make it easier for me to test the Baikal sync.

**Comment by pascal06** [comment]
Hello David,
yes, with pleasure, I can offer you an account.

Your login is : xxxx (lower case)
You password is : xxxx (lower case)

Normaly, you have to use this adress to access the caldav server with 
"tasksync":
http://www.xxx.com/diary/cal.php/calendars/david/default/
This is the same adress that Caldav-Sync http://dmfs.org/caldav/ use 
on Android.
This is used by Thunderbird / Lightning / SoGo connector too 
(http://www.sogo.nu/downloads/frontends.html)

If you want to test something, you can access it with the web interface:
http://www.xxx.com/diary/Calendar/

Thanks in advance.

Best regards,

Pascal

NB: David, I wrote you on your personnal mail. Because I think that it would be better that I keep my Baikal server confidential.

**Comment by David-Development** [comment]
@pascal06 Thank you for offering me the test account! I found the issue why the app shows the "failed to authenticate" message. I fixed it but I can't get the sync working yet (No todos will be recieved). But I'm still working on it.

**Comment by pascal06** [comment]
Hello David,
have you "good" news about Task-Sync & Baikal ????
;)
Thanks in advance.

Best regards,

Pascal

**Comment by David-Development** [comment]
Hello Pascal, 

sorry for the late reply. I tested the connection with your server but I'm not getting any ical files. That's really weird. I setup Baikal (Flat Package - v0.2.7) on my own Server and it's working! :) (Thunderbird - TaskSync). So can try to update your Baikal Version? Hopefully it's working then. I've no idea why the response of your server is empty.

Best regards,
David

**Comment by pascal06** [comment]
Hello David,

it doesn't matter for the time ;)

I'm just upgrading Baikal ;)
So now it runs the 0.2.7 version.

It seem to work, so I think you can test ;)

Best Regards,

Pascal

**Comment by David-Development** [comment]
Does it work for you now? :)

**Comment by pascal06** [comment]
Hello David,
I installed the new version yesterday evening, so effectively the 
connection works now, It can connect to the server and synchronize...
However,
there are still some issues:
I had a lot of old terminated task still present on my server, with 
Thunderbird they appears as terminated too, but not (all) on TaskSync.
I keep on testing ;)
Best regards,

Pascal

**Comment by snte** [comment]
I could not sync with Baikal 0.2.6 too. Updated Baikal to 0.2.7, then uninstalled Task Sync, and reinstalled it. After that it worked. David, thanks for the support.
