### ISSUE TITLE
Unable to sync from OwnCloud

### ISSUE THREAD

**Issue by onny** [David-Development/Task-Sync#17]
I don't know how to debug this so I can just tell that adding the URL of my server (with self-signed cert) works but zero tasks get synced.
I also can't see any request on my nginx access.log.

URL: https://owncloud.example.org/remote.php/caldav/calendars/onny/default%20calendar

I'm able to access this URL in Firefox and can read the VTODO .ics-files.

**Comment by David-Development** [comment]
Sorry for the late reply. Which version of ownCloud do you use? 6.0.2? Which Android OS are you using?
I'm using the TaskSync App only with ownCloud and it's working still fine. So it seems like an individual problem.

**Comment by onny** [comment]
Currently I'm using: 
OwnCloud 6.0.2
Cyanogenmod 10.1.3-p880 (Android 4.2.2)

I've set up a test account on my owncloud instance, I'll send you login creds in a private message. Thanks for your help!

**Comment by onny** [comment]
Even fails with a nightly CyanogenMod version:
11-20140416-NIGHTLY-p880
Android version: 4.4.2
Kernel: 3.1.10-CM+

**Comment by David-Development** [comment]
So I finally figured out what the problem is...
Your SSL-Certificate is expired which isn't accepted by the Apache Commons HttpClient. So you'll have create a new SSL-Certificate. Furthermore you'll have to enter the url with "https", not only "http". Otherwise only valid SSL-Certificates will be accepted.

I hope you can create a new SSL-Certificate?

Here the error message: SSLHandshakeException: current time: Fri Apr 18 15:59:39 MESZ 2014, expiration time: Thu Feb 13 12:20:20 MEZ 2014

**Comment by onny** [comment]
Still no success :( I again mailed you you the configuration details.

**Comment by Pantos** [comment]
I got the same problem since Task Sync 0.3.4. I'm using ownCloud 0.6.3. I made a fresh install from Task Sync. Now I get the error "authentification failed". The SSL certificate is selfsigned and working perfect with other apps. Seems to be a bug...

**Comment by David-Development** [comment]
@Pantos is your server certificate expired? And is your phone rootet?

**Comment by Pantos** [comment]
The server certificate is valid till 27.07.2016. I get this error on my Galaxy S3 (rooted with cyanogenmod) and on my Galaxy Note 10.1 2014 (not rooted). The problem starts with the last app update...

**Comment by David-Development** [comment]
Okay well, did you update your certificate since you used the app the first time? The problem is, that Android saves the ssl certificate and doesn't update the certificate if there is a new one.

**Comment by Pantos** [comment]
I updated my certificate in july 2013. But after this it worked fine...

**Comment by David-Development** [comment]
Please try to access the url of your calendar directly via the browser. If everything works (you should see a list of .ics files) the app should work.

Here a quick example of the problem which I described earlier:
- SSL Certificate 1 - Expiration date: 10.05.2014
- SSL Certificate 2 - Expiration date: 10.05.2015
- Install TaskSync App and connect to your Server - SSL Certificate 1 will be downloaded and stored on your device.
- Change SSL Certificate 1 to SSL Certificate 2
- 11.05.2014 - The first SSL Certificate is expired. Android doesn't update the SSL Certificate automatically.

This is a bug in the Apache HTTP Client. So a possible workarounds are : 

1) Reset Android to factory defaults (not recommend) or
2) Install the App CACertMan and try to delete the certificate manually (root required)

**Comment by tristan-k** [comment]
Same for me. I configured the Account properly, but there are no Tasks synced. Im on a Samsung Galaxy S4 (Cyanogenmod 11 Rooted).

**Comment by Pantos** [comment]
Sorry for my late reply. I just found the problem. OwnCloud shows an incorrect url to the default calendar. 

OwnCloud shows: https://owncloud/remote.php/caldav/calendars/name/default%2520calendar

The correct url is: https://owncloud/remote.php/caldav/calendars/name/default%20calendar

Now it works. Thanks for your help!

**Comment by David-Development** [comment]
I'm glad to hear that it's working now!
I've implemented a new feature which allows you to auto-detect all calendars on your ownCloud instance. You'll only have to type in (as a new account) http[s]://path_to_server/owncloud --> after that a button will appear and you can auto detect all calendars.

@tristan-k Did you try the latest app version?

**Comment by Pantos** [comment]
Very cool feature! Thanks for this great app!
