### ISSUE TITLE
HTTP Status 405

### ISSUE THREAD

**Issue by ghost** [David-Development/Task-Sync#2]
Hello,

I'm using OC 5.0.7 and latest Task Sync. Setting up the oc account was ok. If I adding a new task there is a "Error - HTTP-Status Code 405". If I adding a task over OC web interface the Task-Sync app can't find it or better say don't sync from OC.

**Comment by David-Development** [comment]
Hello ByteLock,

thank you for reporting this issue. Seems that the app can't get a connection to the ownCloud. Are you able to sync other Tasks (not created by ownCloud. e.g. Thunderbird) or is the sync completly broken ?.
Which Url are you using ?

I hope we can solve the problem soon.

Best regards
David

**Comment by ghost** [comment]
Thank you for the fast reply. Syncing over Thunderbird works, in both ways. I'm using a URL of this kind:
https://SERVER/owncloud/remote.php/caldav/calendars/USER

I checked the "Allow non trusted Certificates" (I don't know how it named). My QNAP Certificate is not trusted on other apps. This is a idea. 

It would be nice if I can change the preferences after final setup in your app. Thank you for supporting Owncloud with your app. This is the up-to-date way :)

Ok sorry, I thinks this was not clearly enough. Thunderbird works with owcloud. But Task-Sync don't see anything of this.

**Comment by David-Development** [comment]
The problem is that you've inserted a wrong url.To get it working you have to insert a url which points directly on a calendar. e.g.
[...]/owncloud/remote.php/caldav/calendars/david/default%20calendar

In a future version I've planned that you can modify the account settings.

**Comment by ghost** [comment]
Thank you and sorry for my fault. This works!

Best regards
Christian

**Comment by David-Development** [comment]
You are welcome! I'm glad to hear that the app is working now for you!
