### ISSUE TITLE
Crash in Account Settings.

### ISSUE THREAD

**Issue by noyez** [David-Development/Task-Sync#21]
Platform: Android 4.4.2
Phone: Moto X

To reproduce, go to Settings -> Accounts -> Task Sync -> General Settings -> Account Settings. From the next screen choose any account, and TaskSync crashes. 

Please let me know what other information you might need. I sent a report from the crash screen, but i don't know where that goes. 

Thanks!

**Comment by David-Development** [comment]
Thank you for reporting this issue! I recieved the crash log in my google developer console. I'm going to fix this issue as soon as possible.
