### ISSUE TITLE
Priority problems

### ISSUE THREAD

**Issue by snte** [David-Development/Task-Sync#22]
I am using Baikal (and Thunderbird), and noticed some inconsistencies when assigning priorities:

1)
i created two tasks in Thunderbird, one with high, one with no priority. When syncing and listing in Task Sync (list sort order: priority), it is in correct order. Changing to name sort also reorders the list, so Task Sync 'knows' about the priority.

When viewing or editing the task in Task Sync however, the task with no prio says none (which is OK), but the task with high prio says 'low'. 
When (trying to fix this) i change this to high prio in TS, and sync back, i get a 'Error - HTTP-Status Code: -1'.
When i do some more changes to the entry, sometimes the task even gets corrupt, with empty title.

2)
then i created two tasks in Task Sync, one with high, one with no priority. When syncing and listing in Thunderbird, everything is fine.
Then i change the task with no prio to low prio in Task Sync (no changes made in Thunderbird, just synced), i get  'Error - HTTP-Status Code: -1'.

Thanks for yout support!

**Comment by David-Development** [comment]
Thank you for the report. I try to fix the issue soon.

**Comment by David-Development** [comment]
@snte This issue is fixed, isn't it?
