### ISSUE TITLE
Deleted Accounts after Smartphone restart

### ISSUE THREAD

**Issue by StefanSchafnitzel** [David-Development/Task-Sync#25]
Im using Android on my Smartphone Galaxy S4 mini. Always when my Smartphone makes a restart, all the accounts will be deleted. I need a bug fix or a workaround for that problem.
Best regards,
stefan

**Comment by StefanSchafnitzel** [comment]
Android 4.2.2

**Comment by David-Development** [comment]
There is already a workaround available on Google Play (https://play.google.com/store/apps/details?id=de.luhmer.tasksyncworkaround)
I hope it works for you!
