### ISSUE TITLE
Importing accounts should offer to name the calendar automatically

### ISSUE THREAD

**Issue by aproposnix** [David-Development/Task-Sync#27]
Currently when importing an owncloud account, it'll show a list of the calendars to sync. Once you have selected the calendars to sync, the user is expected to log in for each calendar and name the calendar. This can get VERY confusing (esp., on a mobile) as you have to scroll all the way to the right of the URL for each calendar to see the name. 

It would be better if the import tool automatically populated the calendar name field with the name of the calendar.

**Comment by David-Development** [comment]
Great idea. Will be implemented in the next release.

**Comment by aproposnix** [comment]
Cool. Thanks!

**Comment by David-Development** [comment]
Fixed in 0.4.5. Thanks for the report!
