### ISSUE TITLE
Cannot add additional calendars after initial import

### ISSUE THREAD

**Issue by aproposnix** [David-Development/Task-Sync#28]
When setting up TaskSync, it gives you the option to select which calendars to sync. This is cool, it works.  However, if you later add a new task list on owncloud, there's no way (as far as I can see) to add it without resetting everything. 

EDIT: OK, so you have to go under system settings and click on "add account" and then select Task-Sync. This should be possible from the main app as it can be very confusing.

**Comment by David-Development** [comment]
Yes.. you're right. Thank you for the feedback. I'm going to add a button in the app to add accounts directly from there.
