### ISSUE TITLE
Task disappears from Android app if comment added from OC

### ISSUE THREAD

**Issue by aproposnix** [David-Development/Task-Sync#29]
When using comments from the enhanced tasks app in OC, the task will disappear from the android app.  Going back into the OC task and removing (deleting) the comment/s makes it reappear in the android app.

**Comment by David-Development** [comment]
Thank you for the feedback. I'm going to fix this issue in the next release.

**Comment by aproposnix** [comment]
Hi. Do you have a target release for the bug fix?

**Comment by David-Development** [comment]
I'm trying to fix it today!

**Comment by David-Development** [comment]
It's a problem in the tasks app. I've opened an issue https://github.com/owncloud/tasks/issues/105.

**Comment by David-Development** [comment]
The sync from ownCloud to android should work now. But changing something in the android app duplicates the entry in ownCloud (when using the tasks app). I hope I can fix this in the future.
