### ISSUE TITLE
Sync Clarification

### ISSUE THREAD

**Issue by seul** [David-Development/Task-Sync#30]
Just to be clear: is this one way or two way sync?
- Tasks I create in Owncloud appear in Task Sync and Thunderbird Lightning
- Tasks I create in TB appear in OC and TS
- Tasks I create in TS _do not_ appear in OC nor in TB
- Edits of tasks done in TS disappear after syncing

**Comment by David-Development** [comment]
Thank you for the feedback. The app supports two way sync.
Do you use the Enhanced-Tasks App in ownCloud?

Which Android OS and which ownCloud Version are you using?

**Comment by David-Development** [comment]
Did you try Version 0.4.4? I tried to reproduce this issue - without success. I did some research and tested a lot but it's working for me (two way sync) with ownCloud - Thunderbird (Lightning) - TaskSync.

**Comment by seul** [comment]
Apologies for the delay in replying. The issue went away after a day or two and the app has been working nicely ever since – so it has also been unreproducible on my end for the last months. Thanks for the good work.
