### ISSUE TITLE
Visual indicator of high prio tasks

### ISSUE THREAD

**Issue by armaccloud** [David-Development/Task-Sync#35]
It would be a nice addition to the task app to have a visual indicator of high prio tasks from the task overview. E.g. by placing a red exclamation mark in front of it. This way it is possible to keep oversight of what tasks are high prio in addition to the due date.

**Comment by David-Development** [comment]
Fixed in 0.4.5. I hope you like it. Created a small indicator for low, middle and high prio tasks.

**Comment by armaccloud** [comment]
You've done quite some work on the app I see. Elegant solution for the indicator! :+1:
