### ISSUE TITLE
Tasks missing in app when a Comment was filled in in OC

### ISSUE THREAD

**Issue by sebastian-muthwill** [David-Development/Task-Sync#36]
All Tasks with comments in OC are not shown in APP

OC Version: 7.0.4
OC Task Version: 0.5

App Version: 0.4.6

**Comment by David-Development** [comment]
Thanks for the report. This issue is already fixed and will be available with the next update of the ownCloud tasks app. See https://github.com/owncloud/tasks/issues/105 for more details.
