### ISSUE TITLE
Failed to authenticate

### ISSUE THREAD

**Issue by SpawnY0815** [David-Development/Task-Sync#37]
Hi,

I used the right credentials and url. But cannot login to my owncloud 8.0.3 account.
In owncloud i used the app this app:
https://apps.owncloud.com/content/show.php/Tasks?content=164356&PHPSESSID=8ohvnk98so2bvbs3c8r9ahoen3

The app itself works fine.

Can you help me whit that?

Cheers!
Chris

**Comment by David-Development** [comment]
Do you still need help? Sorry haven't noticed this issue..
