### ISSUE TITLE
Use System Certificate Files

### ISSUE THREAD

**Issue by SecJoe** [David-Development/Task-Sync#39]
Hey,

on Android there is a folder with all Cert-Certs: its in /system/etc/security/cacarts/. I have i owncloud Server and a selfsigned-certificate. So if i wanna add that cert to Android i have to add it in the folder (see above). After that all apps are accepting that Cert (have tried CardDav-Sync, CalDav,Sync...). 

Task-Sync doesnt accept that Cert it seems. The apps outputs the following message: "Failed to authenticate".

**Comment by David-Development** [comment]
Unfortunately the library I'm using for the connection with the server doesn't support these certificates. So you'll need to enable the option "Allow all SSL-Certificates".

**Comment by SecJoe** [comment]
Could you add a funktion to add a cert. I mean a field who i can define a path to my certfile? Otherwise with that "allow all cert..."-option my connection wouldnt be secure. Im a little bit paranoid, so im not so good with that (Allow all) option :)

**Comment by David-Development** [comment]
I already tried to implement an option like this but unfortunately it's not possible with the library I'm using. So the only option is to disable ssl verification or to get a signed certificate. Sorry!

**Comment by SecJoe** [comment]
What library do you use?
In which directory the app does look for certificate files?
Is planned to use another lib in future? It seems that lib is really inflexible...:)

**Comment by David-Development** [comment]
I'm using the Apache HttpURLConnection which is required by the Jackrabbit library. I'm not 100% sure how the library verifies the SSL certificates but as far as I know it should be sufficient to install the SSL certificate in android (I think root is required for this). Unfortunately there is no other library available which supports webdav/caldav for java. So the only possible option would be to write a new library from scratch, which is a little bit overkill and (for time reasons) not possible for me at the moment.
And yes, the library is actually "pretty old" by now and not very well extendable.
